workspace = {}
[package]
edition = "2021"
name = "rust-ssq"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
digest = "0.9"
rand = "0.8.4"
sha2 = "0.9"
